#!/usr/bin/env python3
"""STEP 35-3. Install a public, strictly fictional performance API endpoint.

Requires demo_performance_preview.json generated by demo_performance.py on the
existing demo server. This endpoint MUST NEVER be used for real-account history.
Usage: sudo python3 install_demo_performance_api.py
"""
from __future__ import annotations
import ast
from datetime import datetime, timezone
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
import time
import urllib.request

ROOT = Path('/home/ubuntu/finance-api')
API = ROOT / 'demo_api.py'
DATA = ROOT / 'demo_performance_preview.json'
CONF = Path('/etc/nginx/sites-available/default')
SERVICE = 'finance-demo-api'
DOMAIN = '13-125-71-101.sslip.io'
MARK = '# BJ_DEMO_PERFORMANCE_ENDPOINT_V1'
NG_MARK = '# BJ_DEMO_PERFORMANCE_HTTPS_V1'
ROUTE = '''

# BJ_DEMO_PERFORMANCE_ENDPOINT_V1 - strictly fictional historical simulation
@app.get("/api/demo-performance")
def demo_performance():
    import math
    try:
        raw = json.loads((ROOT / "demo_performance_preview.json").read_text(encoding="utf-8"))
        periods = raw["periods"]
        points = raw["daily_cumulative_returns"]
        if (raw.get("demo") is not True or raw.get("schema_version") != 1
                or raw.get("benchmark") != "SPY" or raw.get("daily_observations") != 252
                or not isinstance(raw.get("assumptions"), str)
                or "Fictional SOXL/MU/COHR" not in raw["assumptions"]
                or set(periods) != {"1M", "3M", "6M", "1Y"}
                or not isinstance(points, list) or len(points) != 253):
            raise ValueError("not the known fictional demo")
        # Never forward the entire local JSON; explicitly construct the output.
        clean_periods = {}
        for window, days in (("1M",21),("3M",63),("6M",126),("1Y",252)):
            period = periods[window]
            if int(period["trading_days"]) != days:
                raise ValueError("invalid period length")
            clean_periods[window] = {
                "trading_days": days,
                "period_start": str(period["period_start"]),
                "period_end": str(period["period_end"]),
            }
            for key in ("portfolio_return_pct", "spy_return_pct", "excess_return_pct",
                        "portfolio_mdd_pct", "spy_mdd_pct"):
                val = float(period[key])
                if not math.isfinite(val) or abs(val) > 100000:
                    raise ValueError("nonfinite or invalid metric")
                clean_periods[window][key] = val
        clean_points = []
        last_date = ""
        for row in points:
            date = str(row["date"])
            if not re.fullmatch(r"\\d{4}-\\d{2}-\\d{2}", date) or date <= last_date:
                raise ValueError("invalid time sequence")
            last_date = date
            p = float(row["portfolio_pct"])
            b = float(row["spy_pct"])
            if not all(math.isfinite(v) and -100 <= v <= 100000 for v in (p,b)):
                raise ValueError("invalid chart values")
            clean_points.append({"date": date, "portfolio_pct": p, "spy_pct": b})
        if (abs(clean_points[0]["portfolio_pct"]) > .00001
                or abs(clean_points[0]["spy_pct"]) > .00001
                or clean_points[0]["date"] != str(raw["period_start"])
                or clean_points[-1]["date"] != str(raw["period_end"])):
            raise ValueError("invalid demo baseline")
        result = {
            "schema_version": 1, "demo": True, "benchmark": "SPY",
            "period_start": clean_points[0]["date"],
            "period_end": clean_points[-1]["date"],
            "daily_observations": 252,
            "calculated_at_utc": str(raw["calculated_at_utc"]),
            "data_source": "Yahoo Finance adjusted historical daily prices (unofficial)",
            "limitations": "Fictional daily-rebalanced demo portfolio, constant FX, zero cash return; excludes costs; not actual account performance.",
            "periods": clean_periods,
            "daily_cumulative_returns": clean_points,
        }
    except (OSError, ValueError, KeyError, TypeError, OverflowError):
        raise HTTPException(status_code=503, detail="DEMO performance snapshot unavailable")
    return JSONResponse(content=result, headers={"Cache-Control":"no-store", "X-Content-Type-Options":"nosniff"})
'''
# Reuse imported `re`? Imported in main installer only; FastAPI module needs own import.
ROUTE = ROUTE.replace('    import math\n', '    import math\n    import re\n')
NG_ROUTE = '''    # BJ_DEMO_PERFORMANCE_HTTPS_V1 - fictional public demo only
    location = /api/demo-performance {
        proxy_pass http://127.0.0.1:8000/api/demo-performance;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 5s;
        proxy_read_timeout 15s;
        add_header X-Content-Type-Options nosniff always;
    }

'''

def cmd(*args):
    return subprocess.run(args, text=True, capture_output=True)

def api_check():
    try:
        with urllib.request.urlopen('http://127.0.0.1:8000/api/demo-performance', timeout=5) as r:
            d = json.load(r)
        return d.get('demo') is True and len(d.get('daily_cumulative_returns', [])) == 253
    except Exception:
        return False

def validate_source():
    if not all(x.is_file() for x in (API, DATA, CONF)):
        raise RuntimeError('Missing demo_api.py, local performance JSON, or nginx default config')
    d = json.loads(DATA.read_text(encoding='utf8'))
    if (d.get('demo') is not True or d.get('schema_version') != 1 or d.get('benchmark') != 'SPY'
        or d.get('daily_observations') != 252 or len(d.get('daily_cumulative_returns', [])) != 253
        or 'Fictional SOXL/MU/COHR' not in d.get('assumptions','')):
        raise RuntimeError('Refusing to expose non-DEMO performance data')
    api = API.read_text(encoding='utf8')
    if '@app.get("/api/demo-risk")' not in api or 'ALLOWED_ORIGIN = "https://mywzhzpk2d-source.github.io"' not in api:
        raise RuntimeError('Unexpected FastAPI structure')
    return api, CONF.read_text(encoding='utf8')

def https_server_insert(conf):
    candidates = []
    for m in re.finditer(r'(?m)^[ \t]*server\s*\{', conf):
        left = conf.index('{', m.start(), m.end()); depth = 1; i = left+1
        while i < len(conf) and depth:
            if conf[i] == '{': depth+=1
            elif conf[i] == '}': depth-=1
            i += 1
        if depth: raise RuntimeError('Unbalanced nginx server block')
        block = conf[left+1:i-1]
        cleaned='\n'.join(row.split('#',1)[0] for row in block.splitlines())
        if (re.search(r'(?m)^\s*server_name\s+'+re.escape(DOMAIN)+r'\s*;', cleaned)
            and re.search(r'(?m)^\s*listen\s+443\s+ssl\s*;', cleaned)
            and re.search(r'(?m)^\s*ssl_certificate\s+', cleaned)):
            match = re.search(r'(?m)^\s*location\s+/\s*\{', block)
            if not match: raise RuntimeError('HTTPS server missing / location')
            candidates.append(left+1+match.start())
    if len(candidates)!=1: raise RuntimeError(f'Expected one HTTPS host; found {len(candidates)}')
    return candidates[0]

def main():
    original_api, original_ng = validate_source()
    if MARK in original_api and NG_MARK in original_ng:
        print('ALREADY INSTALLED; API:', 'OK' if api_check() else 'FAILED')
        return
    if MARK in original_api or NG_MARK in original_ng:
        raise RuntimeError('Partial installation found; stop and inspect before retrying')
    insert = https_server_insert(original_ng)
    candidate_api = original_api.rstrip()+ROUTE+'\n'
    ast.parse(candidate_api)
    candidate_ng = original_ng[:insert]+'\n'+NG_ROUTE+original_ng[insert:]
    ts=datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')
    bapi=API.with_name('demo_api.py.backup-performance-'+ts)
    bng=CONF.with_name('default.backup-performance-'+ts)
    shutil.copy2(API,bapi);shutil.copy2(CONF,bng)
    try:
        API.write_text(candidate_api,encoding='utf8')
        check=cmd(str(ROOT/'.venv/bin/python'),'-m','py_compile',str(API))
        if check.returncode: raise RuntimeError(check.stderr)
        restart=cmd('systemctl','restart',SERVICE)
        if restart.returncode: raise RuntimeError(restart.stderr)
        for _ in range(12):
            if api_check():break
            time.sleep(1)
        else:raise RuntimeError('Local API did not return expected DEMO JSON')
        CONF.write_text(candidate_ng,encoding='utf8')
        test=cmd('nginx','-t')
        if test.returncode:raise RuntimeError(test.stderr)
        reload=cmd('systemctl','reload','nginx')
        if reload.returncode:raise RuntimeError(reload.stderr)
    except Exception as e:
        shutil.copy2(bapi,API);shutil.copy2(bng,CONF)
        cmd('systemctl','restart',SERVICE);cmd('systemctl','reload','nginx')
        raise RuntimeError('Installation failed; configurations restored: '+str(e))
    print('SUCCESS: HTTPS /api/demo-performance installed')
    print('LOCAL API: 200 with 253 DEMO chart points')
    print('BACKUP API:', bapi)
    print('BACKUP NGINX:', bng)
    print('Existing risk routes untouched. Never use public API for real holdings.')

if __name__=='__main__':
    try:main()
    except Exception as error:
        sys.exit('ERROR: '+str(error))
